### PR TITLE
solve `error to parse FLAGS` #127

### PR DESCRIPTION
**Pull request by anarkia7115**
This pull request mainly try to solve #127 

1. Commented FLAGS._parse_flags(), tf.flags.FLAGS have no _parse_flags function in 1.5.0. 
2. Moved 'Data Preparation' part to 'preprocess' function, moved 'Training' part to 'train' function. 
3. Added 'main' function.
4. Added tf.app.run() at the last part of code.

### CODE REVIEW

**Comment by wuyongdec** [comment]
tensorflow      1.8.0      
works！

**Comment by dennybritz** [comment]
Thanks!

**Comment by Kyle-MacKinnon** [comment]
I have tensorflow 1.8.0 but still get this error.

`PS C:\Users\kkmac\Desktop\Spam or Ham\cnn-text-classification-tf> python ./eval.py --eval_train --checkpoint_dir="./runs
/1526268435/checkpoints"
Traceback (most recent call last):
  File "./eval.py", line 31, in <module>
    FLAGS._parse_flags()
  File "C:\Users\kkmac\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "C:\Users\kkmac\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\flags\_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags`

**Comment by Nadedic** [comment]
Same problem like Kyle here, apparently this tensorflow has changed or one pull request changed something else. I mean training works until I manually stop it but the problem with evaluation. How exactly are we gonna ignore flag.parse() function?!

**Pull request merged**
